/**
 * Figure integrity audit (phase 5).
 *
 * The paper must contain real figures generated from experiment data:
 *   1. every figure reference in the tex must point to an existing PNG
 *   2. custom "figure" macros that take a .png argument are a dodge — a
 *      reference that never touches the filesystem compiles fine without
 *      the file and renders a placeholder (found in the first live run)
 *   3. the figure scripts that produce the PNGs must exist
 */

import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

export interface FigureAudit {
  /** Figure file names referenced by the tex (both real and dodgy macros). */
  referenced: string[];
  /** Referenced names with no matching file in figuresDir. */
  missing: string[];
  /** Custom macros (not \\includegraphics) that take a figure-file argument. */
  placeholderMacros: string[];
  /** \\begin{figure} environments containing no file reference at all. */
  envsWithoutFile: number;
  /** Human-readable problems for the reflection feedback (empty = pass). */
  problems: string[];
}

const INCLUDEGRAPHICS = /\\includegraphics\*?(?:\[[^\]]*\])?\{([^}]+)\}/g;
/** Any macro invocation whose argument looks like an image path. */
const MACRO_WITH_IMAGE_ARG = /\\([a-zA-Z]+)\s*\{([^}]*\.(?:png|pdf|jpg|jpeg|eps))\}/g;
const FIGURE_ENV = /\\begin\{figure\*?\}([\s\S]*?)\\end\{figure\*?\}/g;

function normalizeName(raw: string): string {
  // \graphicspath-relative names may or may not carry the extension.
  const name = raw.trim();
  return /\.(png|pdf|jpg|jpeg|eps)$/.test(name) ? name : `${name}.png`;
}

export function auditFigures(tex: string, figuresDir: string, scriptsDir: string): FigureAudit {
  const referenced = new Set<string>();
  const placeholderMacros = new Set<string>();

  for (const m of tex.matchAll(INCLUDEGRAPHICS)) {
    referenced.add(normalizeName(m[1] ?? ""));
  }
  for (const m of tex.matchAll(MACRO_WITH_IMAGE_ARG)) {
    const macro = m[1] ?? "";
    if (macro === "includegraphics") continue;
    placeholderMacros.add(macro);
    referenced.add(normalizeName(m[2] ?? ""));
  }

  const files = existsSync(figuresDir) ? readdirSync(figuresDir) : [];
  const missing = [...referenced].filter((name) => !files.includes(name));

  let envsWithoutFile = 0;
  for (const env of tex.matchAll(FIGURE_ENV)) {
    const body = env[1] ?? "";
    if (!/\\includegraphics/.test(body) && !/\.(png|pdf|jpg|jpeg|eps)/.test(body)) {
      envsWithoutFile++;
    }
  }

  const scripts = existsSync(scriptsDir) ? readdirSync(scriptsDir).filter((f) => f.endsWith(".py")) : [];

  const problems: string[] = [];
  if (placeholderMacros.size > 0) {
    problems.push(
      `[figures] custom macro(s) \\${[...placeholderMacros].join(", \\")} take image arguments — ` +
        `replace them with \\includegraphics{...} (a macro that does not read the file hides missing figures)`,
    );
  }
  if (missing.length > 0) {
    problems.push(`[figures] referenced image files missing from figures/: ${missing.join(", ")}`);
  }
  if (envsWithoutFile > 0) {
    problems.push(`[figures] ${envsWithoutFile} figure environment(s) reference no image file`);
  }
  if (referenced.size > 0 && scripts.length === 0) {
    problems.push(
      "[figures] no scripts/fig_*.py exist — figures must be generated by scripts reading the experiment CSVs",
    );
  }
  if (files.filter((f) => /\.(png|pdf|jpg|jpeg|eps)$/.test(f)).length === 0 && referenced.size === 0) {
    problems.push(
      "[figures] the paper contains no figures at all — add at least one plot generated from the experiment data",
    );
  }

  return { referenced: [...referenced], missing, placeholderMacros: [...placeholderMacros], envsWithoutFile, problems };
}
